//##############################################################################
//###############     This file has been generated by EDROOM     ###############
//##############################################################################
 
 
#include <edroom_glue/edroomdeployment.h>
 
//*****************************************************************************
//Main Wait
 
void MainWait(CCLEDMng   &comp2,
					CCDisplaysMng   &comp3,
					CCSystemMng   &comp4){
 
	Pr_Time waitTime(3, 0);
 
#ifdef _EDROOM_SYSTEM_CLOSE
	while(!comp2.EDROOMIsComponentFinished()
				||!comp3.EDROOMIsComponentFinished()
				||!comp4.EDROOMIsComponentFinished())
#else
	while(true)
#endif

 
		Pr_DelayIn(waitTime);
}
 
//*****************************************************************************
//SetMemory
 
void CEDROOMSystemMemory::SetMemory(){
 
	comp2Memory.SetMemory(10, comp2Messages, &comp2MessagesMarks[0]
					,13,comp2QueueNodes, &comp2QueueNodesMarks[0]);
	comp3Memory.SetMemory(10, comp3Messages, &comp3MessagesMarks[0]
					,13,comp3QueueNodes, &comp3QueueNodesMarks[0]);
	comp4Memory.SetMemory(10, comp4Messages, &comp4MessagesMarks[0]
					,11,comp4QueueNodes, &comp4QueueNodesMarks[0]);
}
 
//*****************************************************************************
//SetComponents
 
void CEDROOMSystemCommSAP::SetComponents(CCLEDMng   *p_comp2,
										CCDisplaysMng   *p_comp3,
										CCSystemMng   *p_comp4){
	mp_comp2=p_comp2;
	mp_comp3=p_comp3;
	mp_comp4=p_comp4;
}
 
 
//*****************************************************************************
//*****************************************************************************
//Signal Translation Functions
//*****************************************************************************
//*****************************************************************************
 
 
TEDROOMSignal CEDROOMSystemCommSAP::C4SystemMng_PDisplaysMngCtrl__C3DisplaysMng_PDisplaysMngCtrl(TEDROOMSignal signalOut){
 
	TEDROOMSignal signalIn;
 
	switch(signalOut){
 
		case( CCSystemMng::SDisplaysStart):	 signalIn=CCDisplaysMng::SDisplaysStart; break;
 
		case( CCSystemMng::SIncreaseDisplays):	 signalIn=CCDisplaysMng::SIncreaseDisplays; break;
 
		default: signalIn=(TEDROOMSignal)(-1); break;
 
	}
	return signalIn;
 
}
 
TEDROOMSignal CEDROOMSystemCommSAP::C3DisplaysMng_PDisplaysMngCtrl__C4SystemMng_PDisplaysMngCtrl(TEDROOMSignal signalOut){
 
	TEDROOMSignal signalIn;
 
	switch(signalOut){
 
		case( CCDisplaysMng::SDisplaysReady):	 signalIn=CCSystemMng::SDisplaysReady; break;
 
		default: signalIn=(TEDROOMSignal)(-1); break;
 
	}
	return signalIn;
 
}
 
TEDROOMSignal CEDROOMSystemCommSAP::C4SystemMng_PLEDMngCtrl__C2LEDMng_PLEDMngCtrl(TEDROOMSignal signalOut){
 
	TEDROOMSignal signalIn;
 
	switch(signalOut){
 
		case( CCSystemMng::SLEDStart):	 signalIn=CCLEDMng::SLEDStart; break;
 
		case( CCSystemMng::SToggleLEDShift):	 signalIn=CCLEDMng::SToggleLEDShift; break;
 
		default: signalIn=(TEDROOMSignal)(-1); break;
 
	}
	return signalIn;
 
}
 
TEDROOMSignal CEDROOMSystemCommSAP::C2LEDMng_PLEDMngCtrl__C4SystemMng_PLEDMngCtrl(TEDROOMSignal signalOut){
 
	TEDROOMSignal signalIn;
 
	switch(signalOut){
 
		case( CCLEDMng::SLEDReady):	 signalIn=CCSystemMng::SLEDReady; break;
 
		case( CCLEDMng::SLEDShiftToggled):	 signalIn=CCSystemMng::SLEDShiftToggled; break;
 
		default: signalIn=(TEDROOMSignal)(-1); break;
 
	}
	return signalIn;
 
}
 
 
 
//*****************************************************************************
//RegisterInterfaces
 
void CEDROOMSystemCommSAP::RegisterInterfaces(){
 
	// Register Interface for Component 2
	m_localCommSAP.RegisterInterface(1, mp_comp2->LEDMngCtrl, mp_comp2);
	m_localCommSAP.RegisterInterface(2, mp_comp2->Timer, mp_comp2);
 
	// Register Interface for Component 3
	m_localCommSAP.RegisterInterface(1, mp_comp3->Timer, mp_comp3);
	m_localCommSAP.RegisterInterface(2, mp_comp3->DisplaysMngCtrl, mp_comp3);
 
	// Register Interface for Component 4
	m_localCommSAP.RegisterInterface(1, mp_comp4->SerialCommand, mp_comp4);
	m_localCommSAP.RegisterInterface(2, mp_comp4->LEDMngCtrl, mp_comp4);
	m_localCommSAP.RegisterInterface(3, mp_comp4->DisplaysMngCtrl, mp_comp4);
 
}
 
 
//*****************************************************************************
////SetLocalConnections
 
void CEDROOMSystemCommSAP::SetLocalConnections(){
 
	m_localCommSAP.Connect(mp_comp4->DisplaysMngCtrl, mp_comp3->DisplaysMngCtrl, connections[0], 
					C4SystemMng_PDisplaysMngCtrl__C3DisplaysMng_PDisplaysMngCtrl, 
					C3DisplaysMng_PDisplaysMngCtrl__C4SystemMng_PDisplaysMngCtrl);
 
	m_localCommSAP.Connect(mp_comp4->LEDMngCtrl, mp_comp2->LEDMngCtrl, connections[1], 
					C4SystemMng_PLEDMngCtrl__C2LEDMng_PLEDMngCtrl, 
					C2LEDMng_PLEDMngCtrl__C4SystemMng_PLEDMngCtrl);
 
}
 
 
//*****************************************************************************
////SetRemoteConnections
 
void CEDROOMSystemCommSAP::SetRemoteConnections(){
 
}
 
//*****************************************************************************
////SetConnections
 
void CEDROOMSystemCommSAP::SetConnections(){
 
	SetLocalConnections();
	SetRemoteConnections();
 
}
 
//*****************************************************************************
////CEDROOMSystemDeployment Constructor
 
CEDROOMSystemDeployment::CEDROOMSystemDeployment(){
 
#ifdef CONFIG_EDROOMSL_ADD_TRACE
#endif
	systemMemory.SetMemory();
 
}
 
//*****************************************************************************
////Config
 
void CEDROOMSystemDeployment::Config(CCLEDMng   *p_comp2,
											CCDisplaysMng   *p_comp3,
											CCSystemMng   *p_comp4){
 
	mp_comp2=p_comp2;
	mp_comp3=p_comp3;
	mp_comp4=p_comp4;
 
	systemCommSAP.SetComponents(	p_comp2,
									p_comp3,
									p_comp4);
 
	systemCommSAP.RegisterInterfaces();
	systemCommSAP.SetConnections();
 
}
 
//*****************************************************************************
////StartComponents
 
void CEDROOMSystemDeployment::StartComponents(){
	mp_comp2->EDROOMStart();
	mp_comp3->EDROOMStart();
	mp_comp4->EDROOMStart();
 
}
 
//*****************************************************************************
////Start
 
void CEDROOMSystemDeployment::Start(){
 
#ifdef CONFIG_EDROOMBP_DEPLOYMENT_NEED_TASK
 
	Pr_Task MainTask(CEDROOMSystemDeployment::main_task,EDROOMprioMINIMUM,1024*16);
 
	kernel.Start();
 
#else
 
StartComponents();
 
	kernel.Start();
 
	MainWait(*mp_comp2,
				*mp_comp3,
				*mp_comp4);
 
 
#endif
 
}
 
#ifdef CONFIG_EDROOMBP_DEPLOYMENT_NEED_TASK
 
	extern CEDROOMSystemDeployment systemDeployment;
 
 
//*****************************************************************************
////main_task
 
 
Pr_TaskRV_t CEDROOMSystemDeployment::main_task(Pr_TaskP_t){
 
	systemDeployment.StartComponents();
	MainWait(*systemDeployment.mp_comp2,
				*systemDeployment.mp_comp3,
				*systemDeployment.mp_comp4);
 
}
#endif
