//##############################################################################
//###############     This file has been generated by EDROOM     ###############
//##############################################################################
 
#ifndef EDROOMDEPLOYMENT_H_
#define EDROOMDEPLOYMENT_H_
 
#include <edroom_glue/edroomdf.h>
#include <public/edroomsl_iface_v1.h>
 
 
//******************************************************************************
// include deployment edroom components
 
#include <public/icuasw_iface_v1.h>
#include <public/ccepdmanager_iface_v1.h>
#include <public/cctm_channelctrl_iface_v1.h>
// ***********************************************************************
// class CEDROOMSystemMemory
// ***********************************************************************
 
class CEDROOMSystemMemory{
 
	//!Messages Memory of component comp1
	CEDROOMMessage	comp1Messages[10];
	bool	comp1MessagesMarks[10];
	CEDROOMQueue::CQueueNode	comp1QueueNodes[13];
	bool	comp1QueueNodesMarks[13];
 
	//!Messages Memory of component comp2
	CEDROOMMessage	comp2Messages[10];
	bool	comp2MessagesMarks[10];
	CEDROOMQueue::CQueueNode	comp2QueueNodes[11];
	bool	comp2QueueNodesMarks[11];
 
	//!Messages Memory of component comp3
	CEDROOMMessage	comp3Messages[10];
	bool	comp3MessagesMarks[10];
	CEDROOMQueue::CQueueNode	comp3QueueNodes[10];
	bool	comp3QueueNodesMarks[10];
 
	public:
 
	ICUASW::CEDROOMMemory comp1Memory;
	CCEPDManager::CEDROOMMemory comp2Memory;
	CCTM_ChannelCtrl::CEDROOMMemory comp3Memory;
 
//!Set Memory
	void SetMemory();
};
 
class CEDROOMSystemCommSAP{
 
	 friend class CEDROOMSystemDeployment;
//!Communication Service Access Point
 
	CEDROOMLocalCommSAP m_localCommSAP;
 
 
//!Conections
 
	CEDROOMLocalConnection connections[1];
 
	ICUASW   * mp_comp1;
	CCEPDManager   * mp_comp2;
	CCTM_ChannelCtrl   * mp_comp3;
 
 
//!Set Components
 
	void SetComponents(ICUASW   *p_comp1,
							CCEPDManager   *p_comp2,
							CCTM_ChannelCtrl   *p_comp3);
 
 
//Signal Conversion
 
	static TEDROOMSignal C2EPDManager_PTMChannelCtrl__C3TM_ChannelCtrl_PTMChannelCtrl(TEDROOMSignal signal);
	static TEDROOMSignal C3TM_ChannelCtrl_PTMChannelCtrl__C2EPDManager_PTMChannelCtrl(TEDROOMSignal signal);
 
 
//!Register Interfaces
	void RegisterInterfaces();
 
//!Set Local Connections
	void SetLocalConnections();
 
//!Set Remote Connections
	void SetRemoteConnections();
 
//!Set Connections
	void SetConnections();
 
};
 
class CEDROOMSystemDeployment{
 
//!Kernel
	Pr_Kernel	kernel;
 
#ifdef CONFIG_EDROOMDEPLOYMENT_NEED_TASK
 
//!Main Task
static Pr_TaskRV_t main_task(Pr_TaskP_t);
 
#endif
	CEDROOMSystemMemory   systemMemory;
	CEDROOMSystemCommSAP  systemCommSAP;
 
	ICUASW   * mp_comp1;
	CCEPDManager   * mp_comp2;
	CCTM_ChannelCtrl   * mp_comp3;
 
	public:
 
	CEDROOMSystemDeployment();
 
//!Deployment Configuration
	void Config(ICUASW   *p_comp1,
					CCEPDManager   *p_comp2,
					CCTM_ChannelCtrl   *p_comp3);
 
//!Deployment Start
	void Start();
 
//!StartComponents
	void StartComponents();
//!Config Components
 
	ICUASW::CEDROOMMemory 		* GetComp1Memory(){return &systemMemory.comp1Memory;}
	CCEPDManager::CEDROOMMemory 		* GetComp2Memory(){return &systemMemory.comp2Memory;}
	CCTM_ChannelCtrl::CEDROOMMemory 		* GetComp3Memory(){return &systemMemory.comp3Memory;}
 
};
#endif
